#!/usr/bin/env python3
"""Admit and merge only verified automation pull requests.

Runs from the trusted default-branch workflow. It never checks out or executes PR code.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Any

API = "https://api.github.com"
TOKEN = os.environ["GH_TOKEN"]
REPO = os.environ.get("REPO") or os.environ["GITHUB_REPOSITORY"]
REQUIRED_WORKFLOWS = [x.strip() for x in os.environ.get("REQUIRED_WORKFLOWS", "").split("|") if x.strip()]

RENOVATE_LOGIN = "renovate[bot]"
KILO_LOGIN = "kilo-code-bot[bot]"
CARRIER_PREFIX = "[autonomy] Repair "

KILO_SENSITIVE_PREFIXES = (
    ".github/workflows/",
    ".github/actions/",
    ".github/CODEOWNERS",
    ".github/dependabot.yml",
    ".mergify.yml",
    "renovate.json",
    ".gitleaks",
    "SECURITY.md",
    "AUTONOMY.md",
    "CI_SETUP.txt",
)
KILO_SENSITIVE_EXACT = {
    "scripts/secret_scan.py",
    "scripts/install_ci_tools.py",
    "scripts/verify_ci_tool_checksums.py",
}


def log(message: str) -> None:
    print(message, flush=True)


@dataclass
class ApiError(RuntimeError):
    status: int
    body: str

    def __str__(self) -> str:
        return f"GitHub API HTTP {self.status}: {self.body[:500]}"


def request(method: str, path: str, data: Any | None = None, expected: tuple[int, ...] = (200,)) -> Any:
    url = path if path.startswith("http") else API + path
    payload = None if data is None else json.dumps(data).encode("utf-8")
    req = urllib.request.Request(url, data=payload, method=method)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("Authorization", f"Bearer {TOKEN}")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    if payload is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read()
            if resp.status not in expected:
                raise ApiError(resp.status, raw.decode("utf-8", "replace"))
            if not raw:
                return None
            return json.loads(raw.decode("utf-8"))
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", "replace")
        raise ApiError(exc.code, body) from exc


def get(path: str) -> Any:
    return request("GET", path, expected=(200,))


def post(path: str, data: Any | None = None, expected: tuple[int, ...] = (200, 201, 202, 204)) -> Any:
    return request("POST", path, data=data, expected=expected)


def issue_labels(pr: dict[str, Any]) -> set[str]:
    return {str(x.get("name", "")) for x in pr.get("labels", [])}


def ensure_label(name: str, color: str, description: str) -> None:
    try:
        post(f"/repos/{REPO}/labels", {"name": name, "color": color, "description": description}, expected=(201,))
    except ApiError as exc:
        if exc.status != 422:  # already exists is returned as validation failure
            raise


def add_labels(number: int, labels: list[str]) -> None:
    post(f"/repos/{REPO}/issues/{number}/labels", {"labels": labels}, expected=(200,))


def comment(number: int, body: str) -> None:
    post(f"/repos/{REPO}/issues/{number}/comments", {"body": body}, expected=(201,))


def list_open_prs() -> list[dict[str, Any]]:
    return get(f"/repos/{REPO}/pulls?state=open&per_page=100")


def list_recent_prs() -> list[dict[str, Any]]:
    return get(f"/repos/{REPO}/pulls?state=all&sort=updated&direction=desc&per_page=100")


def is_same_repo(pr: dict[str, Any]) -> bool:
    return str(pr.get("head", {}).get("repo", {}).get("full_name", "")) == REPO


def is_renovate(pr: dict[str, Any]) -> bool:
    body = pr.get("body") or ""
    return (
        pr.get("user", {}).get("login") == RENOVATE_LOGIN
        and is_same_repo(pr)
        and "This PR was generated by [Mend Renovate]" in body
        and "<!--renovate-debug:" in body
    )


def renovate_automerge_enabled(pr: dict[str, Any]) -> bool:
    return is_renovate(pr) and "**Automerge**: Enabled." in (pr.get("body") or "")


def is_carrier(pr: dict[str, Any]) -> bool:
    labels = issue_labels(pr)
    return (
        is_same_repo(pr)
        and str(pr.get("title", "")).startswith(CARRIER_PREFIX)
        and str(pr.get("head", {}).get("ref", "")).startswith("autonomy/repair-")
        and "autonomy:repair" in labels
    )


def carrier_comments(number: int) -> list[dict[str, Any]]:
    comments: list[dict[str, Any]] = []
    for page in range(1, 11):
        chunk = get(f"/repos/{REPO}/issues/{number}/comments?per_page=100&page={page}")
        comments.extend(chunk)
        if len(chunk) < 100:
            return comments
    raise RuntimeError(f"PR #{number} has too many comments to verify safely")


def linked_kilo_carrier(pr: dict[str, Any], carriers: list[dict[str, Any]]) -> int | None:
    if pr.get("user", {}).get("login") != KILO_LOGIN:
        return None
    pr_url = str(pr.get("html_url", ""))
    body = pr.get("body") or ""
    for carrier in carriers:
        carrier_url = str(carrier.get("html_url", ""))
        if carrier_url and re.search(re.escape(carrier_url) + r"(?!\d)", body):
            return int(carrier["number"])
        try:
            comments = carrier_comments(int(carrier["number"]))
        except ApiError as exc:
            log(f"Carrier #{carrier['number']} comments unavailable: {exc}")
            continue
        for item in comments:
            text = item.get("body") or ""
            if item.get("user", {}).get("login") == KILO_LOGIN and pr_url and re.search(re.escape(pr_url) + r"(?!\d)", text):
                return int(carrier["number"])
    return None


def linked_kilo_review_source(pr: dict[str, Any], sources: list[dict[str, Any]]) -> int | None:
    """Require the trusted router's exact-head receipt before admitting a Kilo PR."""
    if pr.get("user", {}).get("login") != KILO_LOGIN or not is_same_repo(pr):
        return None
    body = pr.get("body") or ""
    for source in sources:
        if source.get("user", {}).get("login") == KILO_LOGIN or not is_same_repo(source):
            continue
        source_url = str(source.get("html_url", ""))
        sha = str(source.get("head", {}).get("sha", ""))
        if not source_url or not re.search(re.escape(source_url) + r"(?!\d)", body) or not sha:
            continue
        try:
            comments = carrier_comments(int(source["number"]))
        except ApiError as exc:
            log(f"Source PR #{source['number']} comments unavailable: {exc}")
            continue
        if any(item.get("user", {}).get("login") == "github-actions[bot]" and
               f"<!-- kilo-auto-repair:{sha}:" in (item.get("body") or "")
               for item in comments):
            return int(source["number"])
    return None


def adopt_linked_kilo_prs(open_prs: list[dict[str, Any]]) -> None:
    recent = list_recent_prs()
    carriers = [pr for pr in recent if is_carrier(pr)]
    for pr in open_prs:
        if pr.get("user", {}).get("login") != KILO_LOGIN:
            continue
        labels = issue_labels(pr)
        if "autonomy:kilo-implementation" in labels:
            continue
        source = linked_kilo_carrier(pr, carriers)
        if source is None:
            source = linked_kilo_review_source(pr, open_prs)
        if source is None:
            log(f"Kilo PR #{pr['number']} has no verified repair source; leaving it untrusted.")
            continue
        add_labels(int(pr["number"]), ["autonomy:repair", "autonomy:kilo-implementation"])
        log(f"Trusted Kilo implementation PR #{pr['number']} linked to source PR #{source}.")


def trusted_kind(pr: dict[str, Any]) -> str | None:
    labels = issue_labels(pr)
    if is_renovate(pr):
        return "renovate"
    if is_carrier(pr):
        return "carrier"
    if pr.get("user", {}).get("login") == KILO_LOGIN and "autonomy:kilo-implementation" in labels and "autonomy:repair" in labels:
        return "kilo"
    return None


def current_pr_for_sha(open_prs: list[dict[str, Any]], sha: str) -> dict[str, Any] | None:
    matches = [pr for pr in open_prs if pr.get("head", {}).get("sha") == sha]
    trusted = [pr for pr in matches if trusted_kind(pr)]
    return trusted[0] if len(trusted) == 1 else None


def admit_waiting_runs(open_prs: list[dict[str, Any]]) -> None:
    payload = get(f"/repos/{REPO}/actions/runs?status=action_required&per_page=100")
    runs = payload.get("workflow_runs", []) if isinstance(payload, dict) else []
    for run in runs:
        sha = str(run.get("head_sha", ""))
        pr = current_pr_for_sha(open_prs, sha)
        if pr is None:
            continue
        kind = trusted_kind(pr)
        run_id = int(run["id"])
        name = str(run.get("name", "workflow"))
        try:
            post(f"/repos/{REPO}/actions/runs/{run_id}/approve", expected=(201,))
            log(f"Approved waiting {name} run {run_id} for trusted {kind} PR #{pr['number']}.")
            continue
        except ApiError as exc:
            if exc.status not in (403, 404, 409, 422):
                raise
            log(f"Approval endpoint did not accept run {run_id} ({exc.status}); trying safe rerun for the same trusted PR.")
        try:
            post(f"/repos/{REPO}/actions/runs/{run_id}/rerun", expected=(201,))
            log(f"Re-requested {name} run {run_id} for trusted {kind} PR #{pr['number']}.")
        except ApiError as exc:
            log(f"Could not automatically admit run {run_id}: {exc}")


def latest_runs_for_sha(sha: str) -> dict[str, dict[str, Any]]:
    query = urllib.parse.urlencode({"head_sha": sha, "event": "pull_request", "per_page": 100})
    payload = get(f"/repos/{REPO}/actions/runs?{query}")
    latest: dict[str, dict[str, Any]] = {}
    for run in payload.get("workflow_runs", []):
        name = str(run.get("name", ""))
        current = latest.get(name)
        if current is None or int(run.get("id", 0)) > int(current.get("id", 0)):
            latest[name] = run
    return latest


def dedup_check_runs(sha: str) -> list[dict[str, Any]]:
    payload = get(f"/repos/{REPO}/commits/{sha}/check-runs?per_page=100")
    latest: dict[tuple[str, str], dict[str, Any]] = {}
    for check in payload.get("check_runs", []):
        key = (str(check.get("name", "")), str(check.get("app", {}).get("slug", "")))
        current = latest.get(key)
        if current is None or int(check.get("id", 0)) > int(current.get("id", 0)):
            latest[key] = check
    return list(latest.values())


def all_required_checks_green(pr: dict[str, Any]) -> tuple[bool, str]:
    sha = str(pr.get("head", {}).get("sha", ""))
    runs = latest_runs_for_sha(sha)
    for name in REQUIRED_WORKFLOWS:
        run = runs.get(name)
        if run is None:
            return False, f"required workflow {name!r} has not run on {sha[:12]}"
        if run.get("status") != "completed" or run.get("conclusion") != "success":
            return False, f"required workflow {name!r} is {run.get('status')}/{run.get('conclusion')}"

    checks = dedup_check_runs(sha)
    if not checks:
        return False, "no check runs are attached to the current head"
    allowed = {"success", "neutral", "skipped"}
    for check in checks:
        status = check.get("status")
        conclusion = check.get("conclusion")
        if status != "completed":
            return False, f"check {check.get('name')!r} is still {status}"
        if conclusion not in allowed:
            return False, f"check {check.get('name')!r} concluded {conclusion}"

    statuses = get(f"/repos/{REPO}/commits/{sha}/status")
    for item in statuses.get("statuses", []):
        if item.get("state") != "success":
            return False, f"commit status {item.get('context')!r} is {item.get('state')}"
    return True, "all required workflows and current checks are green"


def pr_files(number: int) -> list[str]:
    names: list[str] = []
    for page in range(1, 11):
        chunk = get(f"/repos/{REPO}/pulls/{number}/files?per_page=100&page={page}")
        names.extend(str(item.get("filename", "")) for item in chunk)
        if len(chunk) < 100:
            return names
    raise RuntimeError(f"PR #{number} has too many changed files to verify safely")


def sensitive_file(path: str) -> bool:
    if path in KILO_SENSITIVE_EXACT:
        return True
    return any(path == prefix or path.startswith(prefix) for prefix in KILO_SENSITIVE_PREFIXES)


def place_human_hold(pr: dict[str, Any], reason: str) -> None:
    labels = issue_labels(pr)
    if "autonomy:human-hold" not in labels:
        add_labels(int(pr["number"]), ["autonomy:human-hold"])
        comment(int(pr["number"]), f"Trusted automation stopped here and applied `autonomy:human-hold`: {reason}")
    log(f"PR #{pr['number']} requires human review: {reason}")


def current_head_unchanged(number: int, expected_sha: str) -> dict[str, Any] | None:
    current = get(f"/repos/{REPO}/pulls/{number}")
    if current.get("state") != "open" or current.get("head", {}).get("sha") != expected_sha:
        return None
    return current


def has_current_approval(number: int, sha: str) -> bool:
    reviews = get(f"/repos/{REPO}/pulls/{number}/reviews?per_page=100")
    return any(r.get("state") == "APPROVED" and r.get("commit_id") == sha for r in reviews)


def approve_pr(number: int, sha: str) -> None:
    if has_current_approval(number, sha):
        return
    post(
        f"/repos/{REPO}/pulls/{number}/reviews",
        {
            "event": "APPROVE",
            "body": "Trusted automation approval: exact-head CI, CodeQL and repository security checks passed.",
            "commit_id": sha,
        },
        expected=(200, 201),
    )
    log(f"Approved PR #{number} at {sha[:12]} after trusted checks passed.")


def enable_native_auto_merge(number: int) -> None:
    pr = get(f"/repos/{REPO}/pulls/{number}")
    if pr.get("state") != "open":
        return
    if pr.get("auto_merge"):
        log(f"Native auto-merge is already enabled for PR #{number}.")
        return
    proc = subprocess.run(
        ["gh", "pr", "merge", str(number), "--repo", REPO, "--auto", "--squash"],
        text=True,
        capture_output=True,
        env={**os.environ, "GH_TOKEN": TOKEN},
    )
    if proc.returncode != 0:
        combined = (proc.stdout + "\n" + proc.stderr).strip()
        # A race where another trusted actor merged/enabled auto-merge is harmless.
        current = get(f"/repos/{REPO}/pulls/{number}")
        if current.get("state") != "open" or current.get("merged") or current.get("auto_merge"):
            log(f"PR #{number} changed state while native auto-merge was being enabled; no further action needed.")
            return
        raise RuntimeError(f"Could not enable native auto-merge for PR #{number}: {combined}")
    log(f"Requested native GitHub auto-merge / merge-queue handling for PR #{number}.")


def reconcile_pr(pr: dict[str, Any]) -> None:
    kind = trusted_kind(pr)
    if kind is None or pr.get("draft"):
        return
    labels = issue_labels(pr)
    if labels.intersection({"autonomy:human-hold", "autonomy:superseded", "autonomy:obsolete"}):
        return

    if kind == "renovate" and not renovate_automerge_enabled(pr):
        # Major/manual Renovate PRs may run CI automatically, but remain human merge decisions.
        return

    if kind in {"kilo", "carrier"}:
        sensitive = [path for path in pr_files(int(pr["number"])) if sensitive_file(path)]
        if sensitive:
            place_human_hold(pr, "the repair changes governance/security automation files: " + ", ".join(sensitive[:8]))
            return

    if kind == "kilo":
        recent = list_recent_prs()
        carriers = [source for source in recent if is_carrier(source)]
        if (linked_kilo_carrier(pr, carriers) is None and
                linked_kilo_review_source(pr, list_open_prs()) is None):
            log(f"Kilo PR #{pr['number']} no longer has a current verified source; withholding merge.")
            return

    green, reason = all_required_checks_green(pr)
    if not green:
        log(f"PR #{pr['number']} ({kind}) not ready: {reason}.")
        return

    number = int(pr["number"])
    sha = str(pr.get("head", {}).get("sha", ""))
    current = current_head_unchanged(number, sha)
    if current is None:
        log(f"PR #{number} changed while being evaluated; waiting for the next reconciliation.")
        return

    # Renovate and Kilo are distinct identities, so the repair App can provide the trusted review.
    # Carrier PRs are authored by the same repair App and GitHub correctly forbids self-approval.
    if kind in {"renovate", "kilo"}:
        approve_pr(number, sha)
        if current_head_unchanged(number, sha) is None:
            return

    enable_native_auto_merge(number)


def main() -> int:
    if not REQUIRED_WORKFLOWS:
        raise RuntimeError("REQUIRED_WORKFLOWS must list the repository's CI/security workflow names")
    ensure_label("autonomy:kilo-implementation", "5319E7", "Kilo implementation PR linked to an autonomous repair carrier")
    ensure_label("autonomy:human-hold", "FBCA04", "Automation must stop for human action")

    open_prs = list_open_prs()
    adopt_linked_kilo_prs(open_prs)
    open_prs = list_open_prs()  # refresh labels after Kilo correlation
    admit_waiting_runs(open_prs)

    # Reconcile current trusted PRs. Runs admitted above will normally become ready on a later
    # workflow_run completion or scheduled reconciliation.
    for pr in open_prs:
        reconcile_pr(pr)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"::error::{exc}", file=sys.stderr)
        raise
